language: python
python:
  - "3.6"
  - "3.7-dev"
services: postgresql
addons:
  postgresql: '9.6'
env:
   - DATABASE_URL=postgres://postgres@localhost/mktplaceblog
install:
  - pip install -q -r requirements.txt
before_script:
  - python contrib/config_env.py
  - psql -c "CREATE DATABASE mktplaceblog;" -U postgres
  - python manage.py migrate
  - python manage.py collectstatic --no-input
script:
  - coverage run --source='mktplace' manage.py test
  - flake8
before_install:
  - pip install coveralls
after_success:
  - coveralls
